name: Uconomy
version: '${project.version}'
main: net.teamuni.economy.Uconomy
api-version: 1.19
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  돈:
    permission: ucon.money
permissions:
  ucon.money:
    default: true
  ucon.reload:
    default: op
  ucon.manage:
    default: op
