name: Uconomy
version: '${project.version}'
main: net.teamuni.economy.Uconomy
api-version: 1.18
depend: [Vault]
commands:
  돈:
    permission: ucon.money
  uconomy:
    permission: ucon.reload
permissions:
  ucon.money:
    default: true
  ucon.reload:
    default: op
  ucon.manage:
    default: op
